-- MySQL Script generated by MySQL Workbench
-- Fri Oct  8 09:20:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `avicolabarichara` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avicolabarichara` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `avicolabarichara` ;

-- -----------------------------------------------------
-- Table `Details_sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Details_sale` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Details_sale` (
  `id_details_sale` INT NOT NULL AUTO_INCREMENT,
  `quantities` INT NOT NULL,
  `Sale_id_sale` INT NOT NULL,
  `Product_id_product` INT NOT NULL,
  PRIMARY KEY (`id_details_sale`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Expense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Expense` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Expense` (
  `id_expense` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `name_expense` VARCHAR(45) NOT NULL,
  `description_expense` VARCHAR(45) NOT NULL,
  `total_expense` DOUBLE NOT NULL,
  PRIMARY KEY (`id_expense`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Identity_document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Identity_document` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Identity_document` (
  `number_document` VARCHAR(45) NOT NULL,
  `type_document` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`number_document`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Person` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Person` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cellphone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `district` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `identity_document` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name_product` VARCHAR(45) NULL,
  `description_product` VARCHAR(45) NULL,
  `unit_value` DOUBLE NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Report` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `initialDate` DATE NOT NULL,
  `finalDate` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `name_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sale` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Sale` (
  `id_sale` INT NOT NULL AUTO_INCREMENT,
  `Person_identity_document` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sale`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  `Person_identity_document` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
